
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-dining-s25-10
owner: ucsb-cs156-s25
repo_name: proj-dining-s25-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjkwNzI5MjA4","is_bot":false,"login":"mihir-r-kondapalli","name":"Mihir Kondapalli"},"headRefName":"remove_latitude_longitude","number":29,"title":"fixed latitude longitude bug","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-10/pull/29"}]
