
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-dining-s25-10
owner: ucsb-cs156-s25
repo_name: proj-dining-s25-10
pull_requests: [{"author":{"id":"U_kgDOCNoKBA","is_bot":false,"login":"junjiel123","name":"Junjie Liu"},"headRefName":"placeholder-reviews2","number":37,"title":"Placeholder reviews2","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-10/pull/37"},{"author":{"id":"U_kgDOCu9lXQ","is_bot":false,"login":"matthewzhang275","name":""},"headRefName":"mz-auto-approve-reviews","number":35,"title":"Mz - auto approve reviews","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-10/pull/35"},{"author":{"id":"U_kgDOCu9lXQ","is_bot":false,"login":"matthewzhang275","name":""},"headRefName":"mz-post-review-page","number":34,"title":"Mz - post review page & also submit review button implementation","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-10/pull/34"},{"author":{"id":"U_kgDOCu9lXQ","is_bot":false,"login":"matthewzhang275","name":""},"headRefName":"mz-average-score-feature","number":32,"title":"Mz - added average score feature","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-10/pull/32"},{"author":{"id":"U_kgDOCM75PA","is_bot":false,"login":"mHaghighi04","name":""},"headRefName":"mh-frontend-moderator-role","number":31,"title":"mh - added moderator role to backend, and included role in existing test for a mock user.","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-10/pull/31"},{"author":{"id":"U_kgDOB_9cTw","is_bot":false,"login":"andrewc512","name":"Andrew Chen"},"headRefName":"ac-individual-review-endpoint","number":30,"title":"ac - added endpoint to retrieve individual review by id","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-10/pull/30"}]
